# Generated by Django 3.2 on 2021-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('lats', models.FloatField()),
                ('lngs', models.FloatField()),
            ],
        ),
    ]
